m

diff --git a/bin/pstripe b/bin/pstripe
--- a/bin/pstripe
+++ b/bin/pstripe
@@ -135,7 +135,7 @@ pstripe_calc_variables() {
     PSTRIPE_ERRORS="`mktemp -u`"
     ## Client authentication.
     PSTRIPE_SALT="${PSTRIPE_SALT:-pstripe}"
-    PSTRIPE_CACHE="${HOME}/.pstripe-cache"
+    PSTRIPE_CACHE="${PSTRIPE_CACHE:-${HOME}/.pstripe-cache}"
     ## Internationalization.
     CURRENCY="eur"
     if test -n "${h_lang}"; then
@@ -682,6 +682,8 @@ pstripe_recv_verify() {
         "https://api.stripe.com/v1/customers/${customer}" \
         -d metadata[status]="verified" \
         -d metadata[ecode]=""
+
+    echo "${customer}"
 }
 
 ## -----------------------------------------------------------------------------
@@ -791,6 +793,7 @@ pstripe_auths() {
     ## Get ID.
     if test -n "${1}"; then
         local id="$1"
+        shift
     else
         error "Please specify a customer ID."
         return 1
@@ -805,7 +808,8 @@ pstripe_auths() {
             "https://api.stripe.com/v1/customers/${id}" \
             -d expand[]=subscriptions
         if test @"${JSON:-null}" = @"null"; then
-            return 0
+            error "User ${id} not found."
+            return 1
         fi
         jq -r '
         .subscriptions.data[]       |
@@ -814,7 +818,14 @@ pstripe_auths() {
         .price.product
         ' <<< "${JSON}" > "${cache}"
     fi
-    ## Print result.
+    ## Check authorizations.
+    while test -n "${1}"; do
+        if ! grep "^${1}\$" "${cache}" >/dev/null 2>&1; then
+            error "User ${id} not authorized to ${1}"
+            return 1
+        fi
+        shift
+    done
     cat "${cache}"
 }
 pstripe_userinfo_JSON() {
